blank_issues_enabled: true
contact_links:
  - name: "ğŸ’¡ Request a Feature"
    about: Request a new feature or enhancement in a discussions.
    url: https://github.com/cssnr/virustotal-action/discussions/new?category=feature-requests

  - name: "â” Ask a Question"
    about: Ask a general question or start a discussions.
    url: https://github.com/cssnr/virustotal-action/discussions/new?category=q-a

  - name: "ğŸ’¬ Join Discord"
    about: Chat with us about general questions, issues or suggestions.
    url: https://discord.gg/wXy6m2X8wY

  - name: "ğŸ“ Submit Feedback"
    about: Send general feedback through the website.
    url: https://cssnr.github.io/feedback
